import { Providers } from '@/redux/provider';
import { Global } from '@/styles/Global.styled';
import React from 'react';
import { Header } from '@/components/header/Header';
export const metadata = {
  title: 'To-Do',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Global />
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
